version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodejs_ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password